name: C/C++ CI

on:
  push:
    branches: [ "android14" ]
  pull_request:
    branches: [ "android14" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
git clone https://github.com/xiaomi-sm8150-devs/android_kernel_xiaomi_sm8150.git
